version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: postfixadmin
      MYSQL_USER: postfixadmin
      MYSQL_PASSWORD: postfixadmin

  postfixadmin:
    depends_on:
      - db
    image: postfixadmin
    container_name: postfixadmin
    ports:
      - 8000:80
    restart: always
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: db
      POSTFIXADMIN_DB_USER: postfixadmin
      POSTFIXADMIN_DB_NAME: postfixadmin
      POSTFIXADMIN_DB_PASSWORD: postfixadmin
    volumes:
      - ./config.inc.php/config.inc.php:/var/www/html/config.inc.php

  postfix:
    image: catatnight/postfix
    container_name: postfix
    ports:
      - "25:25"
    environment:
      - MAIL_DOMAIN=mail.pt.com
      - MAIL_SERVER_HOSTNAME=mail.pt.com

